monolog:
    channels: ['vk', 'telegram']

    handlers:
        main:
            type: fingers_crossed
            action_level: error
            excluded_http_codes: [404, 405]
            handler: syslog_handler
            channels: ['!vk', '!telegram']

        my_services:
            type: fingers_crossed
            action_level: info
            handler: syslog_handler
            channels: ['vk', 'telegram']

        syslog_handler:
            type: syslog
            ident: '%env(APP_IDENT)%'

        deprecation:
            type: syslog
            ident: '%env(APP_IDENT)%_deprecation'
            channels: [deprecation]
            formatter: monolog.formatter.json
