---
- hosts: shcc
  gather_facts: false
  vars:
    ansistrano_deploy_from: "{{ playbook_dir }}/../"
    ansistrano_deploy_to: "{{ deploy_path }}/shcc"
    ansistrano_after_symlink_tasks_file: "{{ playbook_dir }}/after-symlink.yaml"
    ansistrano_rsync_extra_params: "--exclude='vendor/***' --exclude='var/***' --exclude='.env.*.local' --exclude='.env.local'  --exclude='.git/***'  --exclude='node_modules/***'  --exclude='assets/***'"
    ansistrano_keep_releases: 2
    ansistrano_shared_files:
      - .env.local

    symfony_env: prod
    symfony_console_path: 'bin/console'
    symfony_run_assets_install: false
    symfony_run_assetic_dump: false
    symfony_run_doctrine_migrations: false
  roles:
    - cbrunnkvist.ansistrano-symfony-deploy
